AllCops:
  Exclude:
    - "acceptance/**/*"
    - "google-cloud-spanner.gemspec"
    - "Rakefile"
    - "test/**/*"
    - "lib/google/spanner/*"
    - "lib/google/cloud/spanner/v1/*"
    - "lib/google/cloud/spanner/admin/database/v1/*"
    - "lib/google/cloud/spanner/admin/instance/v1/*"

Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
Style/NumericLiterals:
  Enabled: false
Style/SpaceAroundOperators:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Style/EmptyLines:
  Enabled: false
Style/EmptyElse:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10
Metrics/AbcSize:
  Max: 25
Metrics/MethodLength:
  Max: 20
Metrics/ParameterLists:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/TrivialAccessors:
  Enabled: false
Style/FileName:
  Enabled: false # for lib/google-cloud-spanner.rb file
