source "http://rubygems.org"

gemspec

gem "rake", "~> 11.0"
gem "google-cloud-core", path: "../google-cloud-core"
gem "google-gax",
    git: "git@github.com:googleapis/gax-ruby.git"
gem "gcloud-jsondoc",
    git: "https://github.com/GoogleCloudPlatform/google-cloud-ruby.git",
    branch: "gcloud-jsondoc"
